apiVersion: zeabur.com/v1
kind: Template
metadata:
  name: Prappser
spec:
  description: Prappser server - event-driven application sync with PostgreSQL
  tags:
    - Go
    - PostgreSQL
    - Backend
  readme: |
    # Prappser Server

    Event-driven application sync server with PostgreSQL backend.

    ## Configuration
    - **MASTER_PASSWORD**: Your admin password (plain text, hashed automatically by server)

    ## Endpoints
    - HTTP API: `https://{domain}/api/*`
    - WebSocket: `wss://{domain}/ws`

  variables:
    - key: MASTER_PASSWORD
      type: STRING
      name: Master Password
      description: Plain text admin password (will be hashed by server)
    - key: SERVER_DOMAIN
      type: DOMAIN
      name: Server Domain
      description: Full domain for the server (e.g., myapp.zeabur.app or your custom domain)

  services:
    - name: postgresql
      icon: https://raw.githubusercontent.com/zeabur/service-icons/main/marketplace/postgresql.svg
      template: PREBUILT
      spec:
        source:
          image: postgres:16-alpine
        ports:
          - id: database
            port: 5432
            type: TCP
        volumes:
          - id: data
            dir: /var/lib/postgresql/data
        env:
          POSTGRES_DB:
            default: prappser
          POSTGRES_USER:
            default: postgres
            expose: true
          POSTGRES_PASSWORD:
            default: ${PASSWORD}
            expose: true
          POSTGRES_HOST:
            default: ${CONTAINER_HOSTNAME}
            expose: true
          POSTGRES_PORT:
            default: "5432"
            expose: true

    - name: prappser-server
      icon: https://cdn.simpleicons.org/go/00ADD8
      template: GIT
      dependencies:
        - postgresql
      domainKey: SERVER_DOMAIN
      spec:
        source:
          source: GITHUB
          repo: 925100212
          branch: main
        ports:
          - id: http
            port: 4545
            type: HTTP
        env:
          DATABASE_URL:
            default: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/prappser?sslmode=disable
          MASTER_PASSWORD:
            default: ${MASTER_PASSWORD}
          PORT:
            default: "4545"
          EXTERNAL_URL:
            default: ${ZEABUR_WEB_URL}
          ALLOWED_ORIGINS:
            default: "https://prappser.app"
          LOG_LEVEL:
            default: info
        instructions:
          - type: DOMAIN
            title: API Endpoint
            content: ${ZEABUR_WEB_URL}/api
            category: Endpoints
          - type: DOMAIN
            title: WebSocket
            content: wss://${ZEABUR_WEB_DOMAIN}/ws
            category: Endpoints
